{
 "title": "Marathon: Summary",
 "tags": [
  "marathon",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Interval", "query": "2m, 1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Number of active applications running on each of the Marathon on Marathon (MoM) instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (job) (marathon_apps_active_gauge{job=~\".+\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tasks Running ($min_interval)",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "content": "Shows number of running tasks for each MoM instance.\n\nNumbers may fluctuate but should be relatively flat."
  },
  {
   "title": "Task Running ($min_interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(marathon_tasks_launched_counter{job=~\".+\"}[$min_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 }, "content": "# title" },
  {
   "title": "HTTP traffic (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (job) (marathon_http_requests_size_counter_bytes{job=~\".+\"})",
     "legendFormat": "read  "
    },
    {
     "expr": "max by (job) (marathon_http_responses_size_counter_bytes{job=~\".+\"})",
     "legendFormat": "written  "
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 }, "content": "# title" },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (job) (marathon_deployments_dismissed_counter{job=~\".+\"})",
     "legendFormat": "dismissed  "
    },
    {
     "expr": "max by (job) (marathon_deployments_active_gauge{job=~\".+\"})",
     "legendFormat": "current  "
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 }, "content": "# title" },
  {
   "title": "Launched tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (job) (marathon_tasks_launched_counter{job=~\".+\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime (m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "(marathon_uptime_gauge_seconds{job=~\".+\"})",
     "legendFormat": "{{instance}"
    }
   ]
  }
 ]
}