{
 "title": "Mesos: Resources Summary",
 "tags": [
  "mesos",
  "summary",
  "dc/os",
  "resources"
 ],
 "time": { "from": "now-11h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUs (agent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_mesos_resources_cpus_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mesos_allocator_mesos_resources_cpus_offered_or_allocated)",
     "legendFormat": "Offered or allocated "
    },
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"cpus\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Mesos Resource Summary Hints",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "content": "When an offer is sent to a framework, it is counted as allocated until the framework rejects it. Hence one may see oscillation.\n\nCPU Quota is occasionally reported at 2x it's actual value. This _may_ be because `mesos_exporter` is too slow and reports multiple times within a polling interval causing a double count. TBC."
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_mesos_resources_mem_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mesos_allocator_mesos_resources_mem_offered_or_allocated)",
     "legendFormat": "Offered or allocated "
    },
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"mem\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_mesos_resources_disk_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mesos_allocator_mesos_resources_disk_offered_or_allocated)",
     "legendFormat": "Offered or allocated "
    },
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"disk\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  { "title": "Quota Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPUs quota",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"cpus\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_quota_roles_resources_guarantee{role_name=~\".*\", resource=\"cpus\"}",
     "legendFormat": "{{role_name}}"
    }
   ]
  },
  {
   "title": "Memory quota",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"mem\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_quota_roles_resources_guarantee{role_name=~\".*\", resource=\"mem\"}",
     "legendFormat": "{{role_name}}"
    }
   ]
  },
  {
   "title": "Disk quota",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_allocator_quota_roles_resources_guarantee{resource=\"mem\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_quota_roles_resources_guarantee{role_name=~\".*\", resource=\"mem\"}",
     "legendFormat": "{{role_name}}"
    }
   ]
  }
 ]
}