{
 "title": "Mesos: Agents Summary",
 "description": "Show Mesos Agent metrics on a host",
 "tags": [
  "mesos",
  "agents",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(mesos_slave_uptime_secs, host)"
   },
   {
    "name": "rate",
    "label": "Rate interval",
    "query": "1s,5s,10s,30s,1m,5m,15m,30m,1h,2h,6h,1d,7d"
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent's uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "dthms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(mesos_slave_uptime_secs{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Active frameworks and Running tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_frameworks_active{host=~\"$host\"}",
     "legendFormat": "framworks "
    },
    {
     "expr": "mesos_slave_tasks_running{host=~\"$host\"}",
     "legendFormat": "tasks "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_recovery_errors{host=~\"$host\"}",
     "legendFormat": "On agent recovery"
    },
    {
     "expr": "mesos_slave_container_launch_errors{host=~\"$host\"}",
     "legendFormat": "On container launch"
    },
    {
     "expr": "mesos_slave_invalid_status_updates{host=~\"$host\"}",
     "legendFormat": "For status updates"
    },
    {
     "expr": "mesos_slave_invalid_framework_messages{host=~\"$host\"}",
     "legendFormat": "For framework messages"
    }
   ]
  },
  {
   "title": "Agent registered?",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_slave_registered{host=~\"$host\"}"
    }
   ]
  },
  { "title": "Resources Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "% of allocated resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_cpus_percent{host=~\"$host\"}",
     "legendFormat": "CPUs"
    },
    {
     "expr": "mesos_slave_mem_percent{host=~\"$host\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "mesos_slave_disk_percent{host=~\"$host\"}",
     "legendFormat": "Disk"
    },
    {
     "expr": "mesos_slave_gpus_percent{host=~\"$host\"}",
     "legendFormat": "GPUs"
    }
   ]
  },
  { "title": "Resources Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_cpus_total{host=~\"$host\"} + mesos_slave_cpus_revocable_total{host=~\"$host\"}",
     "legendFormat": "Total CPUs with revocable"
    },
    {
     "expr": "mesos_slave_cpus_used{host=~\"$host\"}",
     "legendFormat": "Used CPUs, non-revocable"
    },
    {
     "expr": "mesos_slave_cpus_revocable_used{host=~\"$host\"}",
     "legendFormat": "Used CPUs, revocable"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_mem_total{host=~\"$host\"} + mesos_slave_mem_revocable_total{host=~\"$host\"}",
     "legendFormat": "Total memory with revocable"
    },
    {
     "expr": "mesos_slave_mem_used{host=~\"$host\"}",
     "legendFormat": "Used memory, non-revocable"
    },
    {
     "expr": "mesos_slave_mem_revocable_used{host=~\"$host\"}",
     "legendFormat": "Used memory, revocable"
    }
   ]
  },
  {
   "title": "Disk allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_disk_total{host=~\"$host\"} + mesos_slave_disk_revocable_total{host=~\"$host\"}",
     "legendFormat": "Total disk with revocable"
    },
    {
     "expr": "mesos_slave_disk_used{host=~\"$host\"}",
     "legendFormat": "Used disk, non-revocable"
    },
    {
     "expr": "mesos_slave_disk_revocable_used{host=~\"$host\"}",
     "legendFormat": "Used disk, revocable"
    }
   ]
  },
  {
   "title": "GPU allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_gpus_total{host=~\"$host\"} + mesos_slave_gpus_revocable_total{host=~\"$host\"}",
     "legendFormat": "Total GPUs with revocable"
    },
    {
     "expr": "mesos_slave_gpus_used{host=~\"$host\"}",
     "legendFormat": "Used GPUs, non-revocable"
    },
    {
     "expr": "mesos_slave_gpus_revocable_used{host=~\"$host\"}",
     "legendFormat": "Used GPUs, revocable"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Active executors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_executors_registering{host=~\"$host\"}",
     "legendFormat": "Registering"
    },
    {
     "expr": "mesos_slave_executors_running{host=~\"$host\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "mesos_slave_executors_terminating{host=~\"$host\"}",
     "legendFormat": "Terminating"
    }
   ]
  },
  {
   "title": "Terminal executors, rate over $rate window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_slave_executors_terminated{host=~\"$host\"}[$rate])",
     "legendFormat": "Terminated"
    },
    {
     "expr": "rate(mesos_slave_executors_preempted{host=~\"$host\"}[$rate])",
     "legendFormat": "Preempted"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Active tasks, rate over $rate window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_slave_tasks_staging{host=~\"$host\"}[$rate])",
     "legendFormat": "Staging"
    },
    {
     "expr": "rate(mesos_slave_tasks_starting{host=~\"$host\"}[$rate])",
     "legendFormat": "Starting"
    },
    {
     "expr": "rate(mesos_slave_tasks_running{host=~\"$host\"}[$rate])",
     "legendFormat": "Running"
    },
    {
     "expr": "rate(mesos_slave_tasks_killing{host=~\"$host\"}[$rate])",
     "legendFormat": "Killing"
    }
   ]
  },
  {
   "title": "Terminal tasks, rate over $rate window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mesos_slave_tasks_finished{host=~\"$host\"}[$rate])",
     "legendFormat": "Finished"
    },
    {
     "expr": "rate(mesos_slave_tasks_failed{host=~\"$host\"}[$rate])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(mesos_slave_tasks_gone{host=~\"$host\"}[$rate])",
     "legendFormat": "Gone"
    },
    {
     "expr": "rate(mesos_slave_tasks_killed{host=~\"$host\"}[$rate])",
     "legendFormat": "Killed"
    },
    {
     "expr": "rate(mesos_slave_tasks_lost{host=~\"$host\"}[$rate])",
     "legendFormat": "Lost"
    }
   ]
  }
 ]
}